server:
  port: 8094
spring:
  application:
    name: EmployeeManagement
  data:
    mongodb:
      uri: mongodb://localhost:27017/leavemanagement
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone : http://localhost:8761/eureka/
  instance:
      hostname: localhost 